### ISSUE TITLE
Выгрузка списка категорий с необязательными параметрами вызывает ошибку с кодом 500

### ISSUE THREAD

**Issue by allustin** [timepad/timepad_api#2]
При указании ID организации и ключа API при получении списка категорий сервер возращает

* HTTP 500 Internal Server Error
* и ответ
```
{"error":"internal_error","refnum":"1419762502_03efe30861fe01f1fe3dfb135c8abc74"}
```

Воспроизведение простое
1. вызываем http://timepad.ru/api/category_getlist - получаем сводную информацию
2. вызываем с тестовыми параметрами http://timepad.ru/api/category_getlist/?code=b4036f21d0aeed9c44775adcc7ff56e0&id=395 (тестовые данные взяты с http://timepad.ru/apitester/category_getlist.html) - **получаем HTTP 500**

P.S. Кстати API тест возвращает 404 при значениях по умолчанию почти на каждом примере.
P.S.S. Смена порядка параметров значения не имеет http://timepad.ru/api/category_getlist/?id=395&code=6781f99eec1281e9aa9f4b54c01a45dd

**Comment by kojoru** [comment]
Здравствуйте!

Это действительно баг на нашей стороне. Извините за это.

Причина ошибки понятна, мы всё поправим и выложим. Как только это случится, я вам напишу.

**Comment by kojoru** [comment]
Мы всё поправили, ваша ссылка теперь работает.
